#!/bin/bash

set -euo pipefail

TERMVECTOR_FILE=/tmp/termvectors-data

curl --fail $(docker port es 9200)/documents/document/_search'?pretty&size=0' -d '
{
    "aggs": {
        "pk": {
            "scripted_metric": {
                "init_script": "params._agg.pks = []",
                "map_script": "params._agg.pks.add(doc.id.value.toString())"
            }
        }
    }
}' | jq '
{
    "ids": .aggregations.pk.value[0].pks,
    "parameters": {
        "fields": [ "fullText" ],
        "offsets": false,
        "positions": false,
        "field_statistics": false
    }
}
' > "${TERMVECTOR_FILE}"

curl --fail -X POST "$(docker port es 9200)/documents/document/_mtermvectors?pretty" -d "@${TERMVECTOR_FILE}"

rm "${TERMVECTOR_FILE}"
